# Generated by Django 4.2.3 on 2023-07-10 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popTopic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poptopic',
            old_name='completed',
            new_name='outOfStock',
        ),
    ]
