# Generated by Django 4.2.3 on 2023-07-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popTopic', '0002_rename_completed_poptopic_outofstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='poptopic',
            name='genre',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poptopic',
            name='size',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
