# Generated by Django 4.2.3 on 2023-07-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popTopic', '0003_poptopic_genre_poptopic_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='poptopic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
    ]
