# Generated by Django 4.2.3 on 2023-07-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popTopic', '0005_alter_poptopic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='poptopic',
            name='price',
            field=models.DecimalField(decimal_places=2, default=45.99, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poptopic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
