# Generated by Django 4.2.3 on 2023-07-11 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('popTopic', '0006_poptopic_price_alter_poptopic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='poptopic',
            name='dateReleased',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
