# Generated by Django 4.2.3 on 2023-07-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popTopic', '0008_poptopic_datecreated_alter_poptopic_datereleased'),
    ]

    operations = [
        migrations.AddField(
            model_name='poptopic',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
