# Generated by Django 4.2.3 on 2023-07-14 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('popTopic', '0009_poptopic_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.JSONField(default=dict)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('zipCode', models.CharField(max_length=20)),
                ('cardNumber', models.CharField(max_length=20)),
                ('expiration', models.CharField(max_length=10)),
                ('cvv', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
