# Generated by Django 4.2.3 on 2023-08-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popTopic', '0011_order_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='poptopic',
            name='generalType',
            field=models.TextField(blank=True, default='Unknown', null=True),
        ),
    ]
